### ISSUE TITLE
Event Class Generation

### ISSUE THREAD

**Issue by xadimousalih** [ivangfr/spring-cloud-stream-elasticsearch#2]
Hi Ivan
How to Generate a new Event Class In the module common news?
For example if a want a new class (BookEvent) like the below what are the steps?

`@org.apache.avro.specific.AvroGenerated
public class NewsEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {...}
`

**Comment by ivangfr** [comment]
Hi @xadimousalih ,

The file [NewsEvent.java](https://github.com/ivangfr/spring-cloud-stream-kafka-elasticsearch/blob/master/commons-news/src/main/java/com/mycompany/commonsnews/avro/NewsEvent.java) is auto-generated.

If you need to change it, change [news-event.avsc](https://github.com/ivangfr/spring-cloud-stream-kafka-elasticsearch/blob/master/commons-news/src/main/resources/avro/news-event.avsc).

Then, run inside `spring-cloud-stream-kafka-elasticsearch` root folder, `./mvnw clean install --projects commons-news`. This command will recreate the `NewsEvent.java`. If not, delete first `NewsEvent.java` and run the command.

Let me know it those steps worked for you.

**Comment by xadimousalih** [comment]
Thank you very much. It's working!
